### ISSUE TITLE
Jenkins artifactory plugin 2.15.0 with exception related to this module

### ISSUE THREAD

**Issue by Pistahh** [jfrog/build-info#161]
Our Jenkins pipeline worked fine on Jenkins 2.60 + Artifactory plugin belonging to that version; after upgrading Jenkins to 2.113 and Artifactory plugin to 2.15.0 we see exceptions related to this module.

With Jenkinsfile:

```
node('ubuntu') {
    stage('Test') {
        def artifactoryServer = Artifactory.server('repo')
        def buildInfo = Artifactory.newBuildInfo()
        def spec = '{"files": [{"regexp": "false","flat": "true","pattern": "xy-local-test/current/*","target": "out/"}]}'
        sh 'mkdir -p out'
        artifactoryServer.download(spec, buildInfo)
        echo "downloaded"
    }
}
```
we get the following exception:
```
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.valueOf(Long.java:803)
	at org.jfrog.build.extractor.clientConfiguration.util.DependenciesDownloaderHelper.downloadArtifactMetaData(DependenciesDownloaderHelper.java:400)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to dev-dops-trns-prl-01
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:998)
		at hudson.FilePath.act(FilePath.java:987)
		at org.jfrog.hudson.pipeline.executors.GenericDownloadExecutor.execution(GenericDownloadExecutor.java:41)
		at org.jfrog.hudson.pipeline.steps.DownloadStep$Execution.run(DownloadStep.java:66)
		at org.jfrog.hudson.pipeline.steps.DownloadStep$Execution.run(DownloadStep.java:46)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Caused: java.io.IOException
	at org.jfrog.build.extractor.clientConfiguration.util.DependenciesDownloaderHelper.downloadArtifactMetaData(DependenciesDownloaderHelper.java:404)
	at org.jfrog.build.extractor.clientConfiguration.util.DependenciesDownloaderHelper.downloadArtifact(DependenciesDownloaderHelper.java:226)
	at org.jfrog.build.extractor.clientConfiguration.util.DependenciesDownloaderHelper.downloadDependencies(DependenciesDownloaderHelper.java:127)
	at org.jfrog.build.extractor.clientConfiguration.util.DependenciesDownloaderImpl.download(DependenciesDownloaderImpl.java:49)
	at org.jfrog.build.extractor.clientConfiguration.util.AqlDependenciesHelper.downloadDependencies(AqlDependenciesHelper.java:46)
	at org.jfrog.build.extractor.clientConfiguration.util.WildcardsDependenciesHelper.retrievePublishedDependencies(WildcardsDependenciesHelper.java:89)
	at org.jfrog.build.extractor.clientConfiguration.util.DependenciesDownloaderHelper.downloadDependencies(DependenciesDownloaderHelper.java:95)
	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.downloadArtifactsBySpec(SpecsHelper.java:97)
	at org.jfrog.hudson.generic.FilesResolverCallable.invoke(FilesResolverCallable.java:49)
	at org.jfrog.hudson.generic.FilesResolverCallable.invoke(FilesResolverCallable.java:21)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2879)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Caused: java.io.IOException: remote file operation failed: /var/jenkins-slave/workspace/jobname at hudson.remoting.Channel@3aaa4eec:dev-dops-trns-prl-01
	at hudson.FilePath.act(FilePath.java:1005)
	at hudson.FilePath.act(FilePath.java:987)
	at org.jfrog.hudson.pipeline.executors.GenericDownloadExecutor.execution(GenericDownloadExecutor.java:41)
	at org.jfrog.hudson.pipeline.steps.DownloadStep$Execution.run(DownloadStep.java:66)
	at org.jfrog.hudson.pipeline.steps.DownloadStep$Execution.run(DownloadStep.java:46)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by yahavi** [comment]
@Pistahh,
Thanks for reporting this issue.
We are looking into it.
