### ISSUE TITLE
getting NullPointerException while trying to use xray

### ISSUE THREAD

**Issue by stephanerenou** [jfrog/build-info#185]
During my pipeline, I am trying to use xray and on some occasions I am getting:
java.lang.NullPointerException
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryXrayClient.parseXrayScanResponse(ArtifactoryXrayClient.java:78)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryXrayClient.execute(ArtifactoryXrayClient.java:101)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryXrayClient.xrayScanBuild(ArtifactoryXrayClient.java:57)
	at org.jfrog.hudson.pipeline.steps.XrayScanBuildStep$Execution.run(XrayScanBuildStep.java:79)
	at org.jfrog.hudson.pipeline.steps.XrayScanBuildStep$Execution.run(XrayScanBuildStep.java:45)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by srinath45** [comment]
Hi stephanerenou,
Even, I am facing the same issue. Have you found any solution for this problem

**Comment by anguswilliams** [comment]
I'm getting the same error also scanning docker build artefacts:
```
java.lang.NullPointerException
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryXrayClient.parseXrayScanResponse(ArtifactoryXrayClient.java:78)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryXrayClient.execute(ArtifactoryXrayClient.java:101)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryXrayClient.xrayScanBuild(ArtifactoryXrayClient.java:57)
	at org.jfrog.hudson.pipeline.scripted.steps.XrayScanBuildStep$Execution.run(XrayScanBuildStep.java:79)
	at org.jfrog.hudson.pipeline.scripted.steps.XrayScanBuildStep$Execution.run(XrayScanBuildStep.java:45)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by barbelity** [comment]
@stephanerenou @anguswilliams,
The NullPointerException you are receiving seem to be caused by an unexpected scan-response received at Jenkins. I have committed a fix which should prevent this exception from throwing.
From [this commit](https://github.com/jfrog/build-info/commit/8c532e2b0832e5556e14511ead11588994e70494), such response will be printed to the build log, and the scan will retry. That way, your build will not fail and we will be able to understand what was received from the scan.

I have created a snapshot version of Jenkins Artifactory Plug-in including this fix, which can be downloaded [from here](https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.1.x-SNAPSHOT/artifactory-3.1.x-20190130.084841-11.hpi). For better troubleshooting, in future comments please specify your versions of Artifactory and Jenkins Artifactory Plugin.

Please let us know if this fix solves your issue.

**Comment by stephanerenou** [comment]
Thanks for the feedback. Unfortunately the environment where we are facing this is a production env where we cannot deploy for the moment snapshot. I guess this would also be part of your next release so I hope to be able to capture those logs at that time and I hope that I would still be able to reproduce that case then.
Sorry about that.
