### ISSUE TITLE
Could not find org.jfrog.buildinfo:build-info-extractor:2.13.x-SNAPSHOT

### ISSUE THREAD

**Issue by ISFELLY** [jfrog/build-info#214]
I have this issu when trying to use the latest version of "build-info-extractor"

 classpath "org.jfrog.buildinfo:build-info-extractor-gradle:latest.release"

Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all artifacts for configuration ':classpath'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1013)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:123)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationArtifactCollection.ensureResolved(DefaultConfiguration.java:1354)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationArtifactCollection.getArtifacts(DefaultConfiguration.java:1326)
        at org.gradle.composite.internal.CompositeBuildClassPathInitializer.execute(CompositeBuildClassPathInitializer.java:40)
        at org.gradle.composite.internal.CompositeBuildClassPathInitializer.execute(CompositeBuildClassPathInitializer.java:28)
        at org.gradle.api.internal.initialization.DefaultScriptClassPathResolver.resolveClassPath(DefaultScriptClassPathResolver.java:37)
        at org.gradle.api.internal.initialization.DefaultScriptHandler.getScriptClassPath(DefaultScriptHandler.java:74)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.defineScriptHandlerClassScope(DefaultPluginRequestApplicator.java:204)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:82)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:184)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:58)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:66)
        ... 76 more
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.jfrog.buildinfo:build-info-extractor:2.13.x-SNAPSHOT.
Searched in the following locations:
  - file:/home/eslem/.m2/repository/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/maven-metadata.xml
  - file:/home/eslem/.m2/repository/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/build-info-extractor-2.13.x-SNAPSHOT.pom
  - file:/home/eslem/.m2/repository/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/build-info-extractor-2.13.x-SNAPSHOT.jar
  - https://ulice.info/repo/libs-release/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/maven-metadata.xml
  - https://ulice.info/repo/libs-release/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/build-info-extractor-2.13.x-SNAPSHOT.pom
  - https://ulice.info/repo/libs-release/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/build-info-extractor-2.13.x-SNAPSHOT.jar
Required by:
    project : > org.jfrog.buildinfo:build-info-extractor-gradle:4.9.2
        at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:108)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:63)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:94)
        at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:62)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.resolve(ComponentState.java:169)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.Comp

**Comment by yahavi** [comment]
Thanks, @ISFELLY, for reporting this issue.
We are now releasing build-info-extractor-gradle 4.9.3. This version will include a fix for this issue.
In the meantime, you can use 4.9.1.

**Comment by ISFELLY** [comment]
thank you  @yahavi i'm using the 4.9.1 and waiting for the new release

**Comment by yahavi** [comment]
@ISFELLY,
build-info-extractor-gradle 4.9.3 is released.
We apologize for the inconvenience caused by this issue.

**Comment by ISFELLY** [comment]
Thank you !

**Comment by ISFELLY** [comment]
it works like a charm.
