### ISSUE TITLE
Publishing with build-info Gradle plugin failed with IllegalStateException

### ISSUE THREAD

**Issue by m-raab** [jfrog/build-info#276]
Publishing configured with org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin in **Gradle 6** failed with the following exception:

`Error during extraction: 
java.lang.IllegalStateException: The configuration :project:annotationProcessor was resolved from a thread not managed by Gradle.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:580)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:569)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
	at org.jfrog.gradle.plugin.artifactory.extractor.GradleBuildInfoExtractor.calculateDependencies(GradleBuildInfoExtractor.java:375)
	at org.jfrog.gradle.plugin.artifactory.extractor.GradleBuildInfoExtractor.extractModule(GradleBuildInfoExtractor.java:341)
	at org.jfrog.gradle.plugin.artifactory.extractor.GradleBuildInfoExtractor.addModule(GradleBuildInfoExtractor.java:276)
	at org.jfrog.gradle.plugin.artifactory.extractor.GradleBuildInfoExtractor.lambda$null$1(GradleBuildInfoExtractor.java:152)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by yahavi** [comment]
Thanks for reporting this issue, @m-raab!
This [pull request](https://github.com/jfrog/build-info/pull/270) resolves this issue.
The fix will be included in the next release.
We will keep you updated.

**Comment by yahavi** [comment]
@m-raab,
Gradle Artifactory plugin 4.11.0 is released.
Feel free to upgrade.
