### ISSUE TITLE
java.lang.NullPointerException with rtNpm install in Container

### ISSUE THREAD

**Issue by Flash1212** [jfrog/build-info#315]
Jenkins

Now that version 3.5.0 is out I've attempted numerous times now to build an NPM app with the artifactory plugin inside a container. 

```
// Create an Artifactory server instance, as described above in this article:
def server = Artifactory.server('jfrog')
// Create and set an Artifactory NPM Build instance:
def rtNpm = Artifactory.newNpmBuild()
// Set dependency resolver:
rtNpm.deployer server: server, repo: 'npm'
rtNpm.resolver server: server, repo: 'npm'
// Disable automatic binary deployment:
rtNpm.deployer.deployArtifacts = false //tried both true and false
def buildInfo = Artifactory.newBuildInfo()
rtNpm.install buildInfo: buildInfo, path: "package.json", args: '–verbose'
 
Artifactory Plugin 3.5.0
Jenkins 2.203
JDK 8u212, 11 & 15
Node 12.x
```

I've been unsuccessful to do so which always ends with the following:

 
```
npm_feature-cicd-216@tmp/artifactory/cache/artifactory-plugin/3.5.0/* org.jfrog.build.extractor.npm.extractor.NpmInstall
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Feb 26, 2020 5:08:48 PM org.jfrog.build.extractor.npm.extractor.NpmBuildInfoLogger error
SEVERE: null
java.lang.NullPointerException
at org.jfrog.build.extractor.npm.extractor.NpmCommand.validateNpmVersion(NpmCommand.java:73)
at org.jfrog.build.extractor.npm.extractor.NpmInstall.execute(NpmInstall.java:51)
at org.jfrog.build.extractor.npm.extractor.NpmCommand.executeAndSaveBuildInfo(NpmCommand.java:111)
at org.jfrog.build.extractor.npm.extractor.NpmInstall.main(NpmInstall.java:78)

java.lang.RuntimeException
at org.jfrog.build.extractor.npm.extractor.NpmCommand.executeAndSaveBuildInfo(NpmCommand.java:113)
at org.jfrog.build.extractor.npm.extractor.NpmInstall.main(NpmInstall.java:78)
 
[org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:274), org.jfrog.hudson.pipeline.common.executors.NpmExecutor.execute(NpmExecutor.java:62), org.jfrog.hudson.pipeline.common.executors.NpmInstallExecutor.execute(NpmInstallExecutor.java:32), org.jfrog.hudson.pipeline.scripted.steps.NpmInstallStep$Execution.run(NpmInstallStep.java:66), org.jfrog.hudson.pipeline.scripted.steps.NpmInstallStep$Execution.run(NpmInstallStep.java:41), org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47), hudson.security.ACL.impersonate(ACL.java:290), org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)]
 
```
I'm following the example used here: https://github.com/yahavi/project-examples/blob/master/jenkins-examples/pipeline-examples/scripted-examples/npm-container-example/Jenkinsfile

 openjdk:8u212-jdk-alpine", "timbru31/java-node" and the same docker file used in the example below but get no where. I suspect the problem is with the "SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder" error as the source here: https://github.com/jfrog/build-info/blob/master/build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmBuildInfoLogger.java says that it will throw an error.

**Comment by Flash1212** [comment]
Found workaround. -> https://www.jfrog.com/jira/browse/HAP-1299

I believe to still be an issue.

**Comment by yahavi** [comment]
@Flash1212, thanks for reporting this issue!
We fixed it. You can find a SNAPSHOT and further explanation in [HAP-1299](https://www.jfrog.com/jira/browse/HAP-1299).
We'll appreciate your feedback for that!

**Comment by Flash1212** [comment]
@yahavi Thanks for the update. I've made comments there regarding the "extra" bin situation. Is that a non-issue for those of us not relying on the NODEJS plugin in Jenkins?

-Thanks

**Comment by yahavi** [comment]
@Flash1212,
Jenkins Artifactory plugin 3.6.0 is released. This version includes fixes to all known issues.
Feel free to upgrade.
We'll appreciate your feedback for that!

**Comment by Flash1212** [comment]
I ended moving to the CLI and haven't gone back to try in the plugin. I believe that Ralf Graf stated that it worked.
