### ISSUE TITLE
Exception: com.fasterxml.jackson.core.JsonGenerato.writeStartArray(Ljava/lang/Object;I)V

### ISSUE THREAD

**Issue by deeTEEcee** [jfrog/build-info#320]
Gradle version: 6.2
com.jfrog.artifactory plugin version: 4.14.1

**What happened**
When I try to run `./gradlew streaming-core:artifactoryPublish` (streaming-core is just my subproject), im getting this error .
```
Execution failed for task ':streaming-core:extractModuleInfo'.
> com.fasterxml.jackson.core.JsonGenerator.writeStartArray(Ljava/lang/Object;I)V

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':streaming-core:extractModuleInfo'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
```

**Comment by deeTEEcee** [comment]
I've gotten my project to work with 4.10.0 and 4.12.0.

If I switch to plugin version 4.13.0, I get a different error.
```
> Task :artifactoryDeploy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':artifactoryDeploy'.
> java.util.concurrent.ExecutionException: java.lang.VerifyError: Stack map does not match the one at exception handler 77
  Exception Details:
    Location:
      com/fasterxml/jackson/databind/deser/std/StdDeserializer._parseDate(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/util/Date; @77: astore
    Reason:
      Type 'com/fasterxml/jackson/core/JsonParseException' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/exc/StreamReadException' (stack map, stack[0])
    Current Frame:
      bci: @69
      flags: { }
      locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
      stack: { 'com/fasterxml/jackson/core/JsonParseException' }
    Stackmap Frame:
      bci: @77
      flags: { }
      locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
      stack: { 'com/fasterxml/jackson/core/exc/StreamReadException' }
    Bytecode:
      0x0000000: 2bb6 0035 aa00 0000 0000 0081 0000 0003
      0x0000010: 0000 000b 0000 007a 0000 0081 0000 0081
      0x0000020: 0000 0034 0000 0041 0000 0081 0000 0081
      0x0000030: 0000 0081 0000 0071 2a2b b600 11b6 0012
      0x0000040: 2cb6 006b b02b b600 4742 a700 223a 052c
      0x0000050: 2ab4 0002 2bb6 006e 126f 03bd 0004 b600
      0x0000060: 70c0 002d 3a06 1906 b600 4c42 bb00 7159
      0x0000070: 21b7 0072 b02a 2cb6 0073 c000 71b0 2a2b
      0x0000080: 2cb6 0074 b02c 2ab4 0002 2bb6 0025 c000
      0x0000090: 71b0
    Exception Handler Table:
      bci [69, 74] => handler: 77
      bci [69, 74] => handler: 77
    Stackmap Table:
      same_frame(@56)
      same_frame(@69)
      same_locals_1_stack_item_frame(@77,Object[#365])
      append_frame(@108,Long)
      chop_frame(@117,1)
      same_frame(@126)
      same_frame(@133)
```
