### ISSUE TITLE
NullPointerException in GradleBuildInfoExtractor when module dependencies are null

### ISSUE THREAD

**Issue by scoumbassa** [jfrog/build-info#389]
**Describe the bug**
When running the artifactoryDeploy task for a single module in a multi-module project, it fails with a NullPointerException, since the module dependencies are null.

Stacktrace:
`Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':artifactoryDeploy'.
Caused by: java.lang.NullPointerException
	at org.jfrog.gradle.plugin.artifactory.extractor.GradleBuildInfoExtractor.lambda$extract$1(GradleBuildInfoExtractor.java:109)
	at org.jfrog.gradle.plugin.artifactory.extractor.GradleBuildInfoExtractor.extract(GradleBuildInfoExtractor.java:106)
	at org.jfrog.gradle.plugin.artifactory.task.DeployTask.prepareAndDeploy(DeployTask.java:114)
	at org.jfrog.gradle.plugin.artifactory.task.DeployTask.collectProjectBuildInfo(DeployTask.java:55)
	at org.jfrog.gradle.plugin.artifactory.task.DeployTask.taskAction(DeployTask.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:727)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)
	at `

**Versions**
Gradle Build Info Extractor 4.17.2
Gradle 6.0.1
Android Gradle Plugin 3.5.3

Question:
1. In which scenario would module dependencies be set to null instead of being just an empty list that is expected?

**Comment by yahavi** [comment]
Thanks for reporting this issue, @scoumbassa.
We created https://github.com/jfrog/build-info/pull/392 to resolve this issue.

We'll keep you updated.

**Comment by scoumbassa** [comment]
@yahavi do you also know in which scenario the dependencies would be null instead of being an empty list? they were usually null when we would run a artifactoryPublish task on a single module, instead of running on a project level.

**Comment by yahavi** [comment]
@scoumbassa,
It seems like the dependencies are null [at the beginning](https://github.com/jfrog/build-info/blob/build-info-extractor-2.19.3/build-info-api/src/main/java/org/jfrog/build/api/Module.java#L47).
However in multi-module builds, it is possible that [appending](https://github.com/jfrog/build-info/blob/build-info-extractor-2.19.3/build-info-api/src/main/java/org/jfrog/build/api/Module.java#L133) other module's dependencies would erase the null.
Same goes for the artifacts.

**Comment by yahavi** [comment]
@scoumbassa 
Gradle Artifactory plugin 4.18.0 is released. Feel free to upgrade.
We'd appreciate your feedback for that!
