### ISSUE TITLE
All publish tasks fail with: Unrecognized field "slf"

### ISSUE THREAD

**Issue by bedge** [jfrog/build-info#511]
**Describe the bug**

Using an Upload Spec Schema as defined here: 

https://www.jfrog.com/confluence/display/JFROG/Using+File+Specs
https://jfrog.com/knowledge-base/what-are-the-best-practices-and-tips-for-working-with-debian/

ceased working with a jFrog SAAS repo as of June 1 across all projects and build jobs.

**To Reproduce**

Call this groovy script from a jenkins build job to upload a debian package:
```
def jFrogPushDeb(pkgName, distribution, repo, credentials) {
    // https://www.jfrog.com/confluence/display/JFROG/Scripted+Pipeline+Syntax
      def repoURL = "https://XXXXXX.jfrog.io/artifactory/${repo}"
    def component = 'main'
    def server = Artifactory.newServer url: repoURL, credentialsId: credentials
    // https://jfrog.com/knowledge-base/what-are-the-best-practices-and-tips-for-working-with-debian/
    def uploadSpec = """{
                          "files": [
                            {
                              "pattern": "${pkgName}*.deb",
                              "target": "pool/${component}/${pkgName.take(1)}/${pkgName}/",
                              "props": "deb.distribution=${distribution};deb.component=${component};deb.architecture=amd64"
                            }
                         ]
                        }"""
    // Fail build on no upload
    println("uploadSpec:${uploadSpec}")
    server.upload spec: uploadSpec, failNoOp: true
}
```

**Expected behavior**

Until June 1, the response was:
```
17:33:28  [consumer_0] Deploying artifact: https://XXXXXX.jfrog.io/artifactory/ase-tex-debian/pool/main/n/nghc-panel-design/nghc-panel-design_1%3A5.3-18_amd64.deb
```
After june 1, the response is:
```

14:13:49  [consumer_0] Deploying artifact: pool/main/n/nghc-panel-design/nghc-panel-design_0%3A5.3-PR%7E62-SNAPSHOT_amd64.deb;deb.component=main;vcs.revision=8d6076971601dc8adcdfec489a1e78f6bd65a1ea;deb.distribution=bionic;deb.architecture=amd64;build.timestamp=1622668415806;build.name=NGHC+%3A%3A+nghc-panel-design-build+%3A%3A+PR-62;build.number=2;vcs.url=https%3A%2F%2Fghe-rss.roche.com%2Ftarget-enrichment%2Fnghc_panel_design.git
14:13:53  [consumer_0] An exception occurred during execution:
14:13:53  java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "slf" (class org.jfrog.build.client.ArtifactoryUploadResponse), not marked as ignorable (12 known properties: "checksums", "size", "repo", "downloadUri", "path", "statusLine", "created", "errors", "uri", "mimeType", "createdBy", "originalChecksums"])
14:13:53   at [Source: (org.apache.http.conn.EofSensorInputStream); line: 2, column: 12] (through reference chain: org.jfrog.build.client.ArtifactoryUploadResponse["slf"])
14:13:53  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
14:13:53  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
14:13:53  	at java.lang.Thread.run(Thread.java:748)
14:13:53  Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "slf" (class org.jfrog.build.client.ArtifactoryUploadResponse), not marked as ignorable (12 known properties: "checksums", "size", "repo", "downloadUri", "path", "statusLine", "created", "errors", "uri", "mimeType", "createdBy", "originalChecksums"])
14:13:53   at [Source: (org.apache.http.conn.EofSensorInputStream); line: 2, column: 12] (through reference chain: org.jfrog.build.client.ArtifactoryUploadResponse["slf"])
14:13:53  	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
14:13:53  	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
14:13:53  	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
14:13:53  	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
14:13:53  	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
14:13:53  	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
14:13:53  	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
14:13:53  	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
14:13:53  	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
14:13:53  	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3585)
14:13:53  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.setResponse(Upload.java:64)
14:13:53  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.processResponse(JFrogService.java:158)
14:13:53  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:137)
14:13:53  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:76)
14:13:53  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:246)
14:13:53  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:241)
14:13:53  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
14:13:53  	... 2 more
14:13:53  
```

**Versions**
- Extractor version: 
- Operating system: N/A, jenkins 
- Artifactory Version: SAAS jFrog service

**Comment by bedge** [comment]
ref: https://github.com/jfrog/build-info/issues/506

**Comment by eyalbe4** [comment]
@bedge,
Thanks for reporting this issue!
You didn't specify the Jenkins Artifactory Plugin you're using, but I believe the latest release resolves this issue. 
Please let us know if it doesn't.

**Comment by bedge** [comment]
@eyalbe4 
We had 3.11.2 of the jenkins artifactory plugin installed.
Will try updating. 
I had it in my head that this was on the jFrog side so I didn't spec the jenkins details, but you are absolutely correct in that being a common path that this is all using.
thanks.

**Comment by eyalbe4** [comment]
@bedge,
Will you be able to upgrade to 3.11.4 and let us know if this resolves the issue?

**Comment by bedge** [comment]
Confirmed, fixed.
Thanks again for the guidance.
