### ISSUE TITLE
Exception is thown when using Artifactory Plugin in Jenkins

### ISSUE THREAD

**Issue by white-speedy** [jfrog/build-info#52]
I am using Artifactory Plugin in Jenkins Maven Project (multi module). While Job is runing NPE is thrown from org.jfrog.build.extractor.maven.BuildInfoRecorder#getExtension. Looking on the code, this is really bug because NULL check is implemented after parameter access .

```
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
    at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:142)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
    at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
    at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
    at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
    at hudson.remoting.UserRequest.perform(UserRequest.java:121)
    at hudson.remoting.UserRequest.perform(UserRequest.java:49)
    at hudson.remoting.Request$2.run(Request.java:325)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.jfrog.build.extractor.maven.BuildInfoRecorder.getExtension(BuildInfoRecorder.java:610)
    at org.jfrog.build.extractor.maven.BuildInfoRecorder.addDependenciesToCurrentModule(BuildInfoRecorder.java:594)
    at org.jfrog.build.extractor.maven.BuildInfoRecorder.addFilesToCurrentModule(BuildInfoRecorder.java:460)
    at org.jfrog.build.extractor.maven.BuildInfoRecorder.finalizeAndAddModule(BuildInfoRecorder.java:446)
    at org.jfrog.build.extractor.maven.BuildInfoRecorder.finalizeModule(BuildInfoRecorder.java:376)
    at org.jfrog.build.extractor.maven.BuildInfoRecorder.projectSucceeded(BuildInfoRecorder.java:196)
    at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:74)
    at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:91)
    ... 27 more
```

I do not know why it happens in one of our project.

**Comment by adetalhouet** [comment]
I'm kind of hitting the same issue here.
I have a maven jenkins job that is correctly setup. Running the job without the "Deploy artifacts to Artifacotry" is working perfectly, but when enabling the plugin, I'm having this NPE:

[ERROR] NullPointerException
java.lang.NullPointerException
	at org.jfrog.build.api.builder.BuildInfoMavenBuilder.mergeModuleDependencies(BuildInfoMavenBuilder.java:379)
	at org.jfrog.build.api.builder.BuildInfoMavenBuilder.mergeModule(BuildInfoMavenBuilder.java:323)
	at org.jfrog.build.api.builder.BuildInfoMavenBuilder.addModule(BuildInfoMavenBuilder.java:280)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.addFilesToCurrentModule(BuildInfoRecorder.java:462)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.finalizeAndAddModule(BuildInfoRecorder.java:446)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.finalizeModule(BuildInfoRecorder.java:376)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.projectSucceeded(BuildInfoRecorder.java:196)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:74)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:126)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven32Launcher.main(Maven32Launcher.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:325)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Artifactory 3.4.1
Jenkins ver. 1.609.2
Artifactory Plugin 2.3.1

**Comment by shikloshi** [comment]
Hi,

Thanks for reporting this issues.
The first one was fixed and will be released on the next Jenkins release (you can track it [here](https://www.jfrog.com/jira/browse/BI-203)).

@adetalhouet - I will investigate the second issue. 
If you have any other details on how you reproduce it issue feel free to let me know.

Thanks,
Aviad.

**Comment by nfalco79** [comment]
The same here.
- Jenkins 2.32.3
- Maven plugn latest version
- Job type maven
- Maven 3.3.9
- our project has a maven parent pom with 10 modules
```
[main] ERROR org.apache.maven.cli.MavenCli - NullPointerException
java.lang.NullPointerException
	at org.jfrog.build.api.builder.BuildInfoMavenBuilder.mergeModuleDependencies(BuildInfoMavenBuilder.java:400)
	at org.jfrog.build.api.builder.BuildInfoMavenBuilder.mergeModule(BuildInfoMavenBuilder.java:344)
	at org.jfrog.build.api.builder.BuildInfoMavenBuilder.addModule(BuildInfoMavenBuilder.java:301)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.addFilesToCurrentModule(BuildInfoRecorder.java:486)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.finalizeAndAddModule(BuildInfoRecorder.java:470)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.finalizeModule(BuildInfoRecorder.java:398)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.projectSucceeded(BuildInfoRecorder.java:214)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:74)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:126)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by nfalco79** [comment]
Your example works, but it is too simple.
We fall in this NPE randomly but now it happens every build also changing plugion version and kind of job (free style/maven style). This block the the deploy on organization (licensed) artifactory.

After a long session of debug the issue happens on our "distribution" module (package of kind "pom") placed in a profile (virgo WAS profile). Inside that module we use the maven-assembly-plugin (3.0.0) to generate a zip archive to gather all dependencies.

Follow the `toString()` of the maven **project** dependencies:
```
[org.apache.felix:org.apache.felix.ipojo:jar:1.8.4:, org.slf4j:osgi-over-slf4j:jar:1.7.2:, ch.qos.logback:logback-classic:jar:1.0.7:provided, ch.qos.logback:logback-core:jar:1.0.7:provided, org.slf4j:jcl-over-slf4j:jar:1.7.2:provided, org.slf4j:jul-to-slf4j:jar:1.7.2:provided, org.slf4j:log4j-over-slf4j:jar:1.7.2:provided, org.slf4j:slf4j-api:jar:1.7.2:provided, org.apache.servicemix.specs:org.apache.servicemix.specs.jaxb-api-2.2:jar:2.7.0:, org.apache.geronimo.specs:geronimo-stax-api_1.0_spec:jar:1.0.1:compile, org.apache.geronimo.specs:geronimo-activation_1.1_spec:jar:1.1:compile, com.google.inject:guice:jar:4.1.0:, javax.inject:javax.inject:jar:1:compile, aopalliance:aopalliance:jar:1.0:compile, org.eclipse.persistence:javax.persistence:jar:2.1.0:, org.eclipse.persistence:org.eclipse.persistence.oracleddlparser:jar:2.5.2:, org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.3:, org.eclipse.persistence:org.eclipse.persistence.oracle:jar:2.5.2:, org.apache.servicemix.bundles:org.apache.servicemix.bundles.javax-inject:jar:1_2:, org.codehaus.jackson:jackson-jaxrs:jar:1.9.2:, org.apache.servicemix.bundles:org.apache.servicemix.bundles.aopalliance:jar:1.0_6:, org.apache.servicemix.bundles:org.apache.servicemix.bundles.xerces:jar:2.11.0_1:, org.codehaus.jackson:jackson-mapper-asl:jar:1.9.2:, org.jboss.spec.javax.annotation:jboss-annotations-api_1.1_spec:jar:1.0.1.Final:provided, org.eclipse.persistence:org.eclipse.persistence.core:jar:2.5.2:, org.apache.servicemix.specs:org.apache.servicemix.specs.activation-api-1.1:jar:2.7.0:, org.eclipse.persistence:org.eclipse.persistence.jpa:jar:2.5.2:, org.joda:joda-money:jar:0.9:, com.sun.jersey.contribs:jersey-multipart:jar:1.19.1:, org.jvnet.mimepull:mimepull:jar:1.9.3:, org.eclipse.persistence:org.eclipse.persistence.oracle.nosql:jar:2.5.2:, org.eclipse.persistence:org.eclipse.persistence.asm:jar:2.5.2:, org.eclipse.persistence:org.eclipse.persistence.jpa.jpql:jar:2.5.2:, com.hazelcast:hazelcast:jar:3.6.4:, org.json:json:jar:20160212:, org.apache.servicemix.specs:org.apache.servicemix.specs.jsr303-api-1.0.0:jar:2.7.0:, com.google.guava:guava:jar:19.0:, org.codehaus.jackson:jackson-xc:jar:1.9.2:, com.thedigitalstack:com.thedigitalstack.org.assertj:jar:1.7.1:, org.hibernate:hibernate-validator:jar:4.3.2.Final:, javax.validation:validation-api:jar:1.0.0.GA:compile, org.apache.servicemix.specs:org.apache.servicemix.specs.scripting-api-1.0:jar:2.7.0:, ...]
```

As you can see some dependencies, for some reason, has scope set to empty string. Their scope is the [default](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope).

The fix in BuildInfoRecorder is easy, in the method `mergeProjectDependencies(Set<Artifact>)` like you do for classifier where you check is if it null and set to empty string, the same you should for scope, set to [default](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) if is empty string.

**Comment by nfalco79** [comment]
this issue could be closed
