### ISSUE TITLE
Build succeeds in Jenkins but then fails at the very end with 'Unrecognized field "deploySucceeded"'

### ISSUE THREAD

**Issue by novasbc** [jfrog/build-info#542]
**Describe the bug**
We are moving past v4.23.4 due to the memory issues described [here](https://github.com/jfrog/build-info/issues/487).  

If we move to the latest (v4.24.14), our Jenkins pipeline builds appear to succeed, only then to fail at the end:

`BUILD SUCCESSFUL in 16s
245 actionable tasks: 245 executed
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to -build-machine-
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1157)
		at hudson.FilePath.act(FilePath.java:1146)
		at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo.getAndAppendDeployableArtifactsByModule(BuildInfo.java:215)
		at org.jfrog.hudson.pipeline.common.executors.GradleExecutor.execute(GradleExecutor.java:73)
		at org.jfrog.hudson.pipeline.scripted.steps.ArtifactoryGradleBuild$Execution.runStep(ArtifactoryGradleBuild.java:76)
		at org.jfrog.hudson.pipeline.scripted.steps.ArtifactoryGradleBuild$Execution.runStep(ArtifactoryGradleBuild.java:63)
		at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
hudson.remoting.ProxyException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "deploySucceeded" (class org.jfrog.build.client.DeployableArtifactDetail), not marked as ignorable (3 known properties: "sourcePath", "artifactDest", "sha1"])
 at [Source: (File); line: 1, column: 346] (through reference chain: java.util.LinkedHashMap["ldapmgr"]->java.util.ArrayList[0]->org.jfrog.build.client.DeployableArtifactDetail["deploySucceeded"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3433)
	at org.jfrog.build.extractor.clientConfiguration.deploy.DeployableArtifactsUtils.loadDeployableArtifactsByModuleFromFile(DeployableArtifactsUtils.java:63)
	at org.jfrog.build.extractor.clientConfiguration.deploy.DeployableArtifactsUtils.loadDeployableArtifactsFromFile(DeployableArtifactsUtils.java:51)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo$DeployPathsAndPropsCallable.invoke(BuildInfo.java:370)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo$DeployPathsAndPropsCallable.invoke(BuildInfo.java:349)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3313)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE`

We appear to be able to revert to 4.24.2 and not get the memory error, yet are able to still build & publish successfully.

**To Reproduce**
* Create a jenkins based github organization pipeline build project
* Attempt to build & publish with v4.24.14.

**Expected behavior**
Publish and build should work successfully with no error.

**Versions**
- Extractor version: 4.24.14
- Operating system: CentOS
- Artifactory Version: 6.23.19

**Additional context**

**Comment by yahavi** [comment]
@novasbc thanks for reporting this issue. 
Could you please provide your Jenkins Artifactory plugin's version? This issue is expected to be fixed in the last patch, 3.12.5.

**Comment by yahavi** [comment]
@novasbc,
Feel free to upgrade to get this issue fixed.
We'd appreciate your feedback on that.
