### ISSUE TITLE
Support gradle 7+

### ISSUE THREAD

**Issue by kilinochi** [jfrog/build-info#651]
I had switched my project to the gradle 7.4.2, but when I had built them, I got next error

```> Task :artifactoryDeploy FAILED
:artifactoryDeploy (Thread[Execution worker for ':' Thread 17,5,main]) completed. Took 5.9 secs.
Closing Git repo: /usr/share/jenkins/fca387fa-1c1f-4eca-a7c6-080cb9dde225/.git
Closing Git repo: /usr/share/jenkins/fca387fa-1c1f-4eca-a7c6-080cb9dde225/.git

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':artifactoryDeploy'.
> java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/gradle/internal/concurrent/GradleThread

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':artifactoryDeploy'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
	at `org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
```
I see you still use gradle 5+, maybe you could think about support gradle 7+ ?

**Comment by Sreemanth** [comment]
@kilinoch
 Use below version issue will be fixed.
`
classpath group: 'org.jfrog.buildinfo', name: 'build-info-extractor-gradle', version: '4.31.2'
`
